<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
// See www.syriacdictionary.net/index.cgi?langsel=en&word=

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> 'FlorinCB aka OryNider, ..., ',
	'DIRECTION'			=> 'ltr',
	'DATE_FORMAT'		=> '|d M Y|',	// 01 Jan 2019 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|d M Y, H:i|',	// 01 Jan 2019, 13:37 (with Relative days enabled)
	'USER_LANG'			=> 'sy-lat',

	// You can define different rules for the determination of plural forms here.
	// See http://wiki.phpbb.com/Plural_Rules for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> 'iēumāe ḥēd',
	'1_MONTH'		=> 'iērēḥ ḥēd',
	'1_YEAR'		=> 'şēnṭāe ḥēd', 
	'2_WEEKS'		=> 'teretein şabate', 
	'3_MONTHS'		=> 'tēltāe iērḥin', 
	'6_MONTHS'		=> 'phēlgut  şēnṭāe',  
	'7_DAYS'		=> 'şabēa iēumin', 

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'Your account has already been activated.',
	'ACCOUNT_DEACTIVATED'			=> 'Your account has been manually deactivated and is only able to be reactivated by an administrator.',
	'ACCOUNT_NOT_ACTIVATED'			=> 'ḥbund adiinle huphal.',
	'ACP'							=> 'Administration Control Penel',
	'ACP_SHORT'						=> 'ACP',
	'ACTIVE'						=> 'Phail',
	'ACTIVE_ERROR'					=> 'The specified username is currently inactive. If you have problems activating your account, please contact a board administrator.',
	'ADMINISTRATOR'					=> 'Administrator',
	'ADMINISTRATORS'				=> 'Administrators',
	'AGE'							=> 'Dēe', //dērēe // 'gfēiflē'
	'AIM'							=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX error',
	'AJAX_ERROR_TEXT'				=> 'Something went wrong when processing your request.',
	'AJAX_ERROR_TEXT_ABORT'			=> 'User aborted request.',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> 'Your request timed out; please try again.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> 'Something went wrong with the request and the server returned an invalid reply.',
	'ALLOWED'						=> 'Murâşh',
	'ALL_FILES'						=> 'Koēl rknphr̈e', //şphüphēinēe   // knphr̈e
	'ALL_FORUMS'					=> 'Koēl dphurumin',
	'ALL_MESSAGES'					=> 'Koēl dhudaut',
	'ALL_POSTS'						=> 'Koēl dhudaut',
	'ALL_TIMES'						=> 'Koēl djmni h <spen title="%2$s">%1$s</spen>',
	'ALL_TOPICS'					=> 'Koēl hnuşein',
	'ALT_TEXT'						=> 'Mâlîl ḥâluphi',
	'AND'							=> 'Uē',
	'ARE_WATCHING_FORUM'			=> 'You have subscribed to be notified of new posts in this forum.',
	'ARE_WATCHING_TOPIC'			=> 'You have subscribed to be notified of new posts in this topic.',
	'ASCENDING'						=> 'Ascending',
	'ATTACHMENTS'					=> 'Attachments',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'The image file you tried to attach is invalid.',
	'AUTHOR'						=> 'Author',
	'AUTH_NO_PROFILE_CREATED'		=> 'The creation of a user profile was unsuccessful.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> 'Invalid database entry.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'Invalid service type provided to OAuth service handler.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'OAuth service not created',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> 'Facebook',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> 'Google',
	'AUTH_PROVIDER_OAUTH_SERVICE_TWITTER'					=> 'Twitter',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'OAuth token not stored.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'OAuth token incorrectly stored.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'The upload was rejected because the uploaded file was identified as a possible attack vector.',
	'AVATAR_DISALLOWED_EXTENSION'	=> 'This file cannot be displayed because the extension <strong>%s</strong> is not allowed.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> 'The specified avatar could not be uploaded because the remote data appears to be invalid or corrupted.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'The uploaded avatar file is empty.',
	'AVATAR_INVALID_FILENAME'		=> '%s is an invalid filename.',
	'AVATAR_NOT_UPLOADED'			=> 'Avatar could not be uploaded.',
	'AVATAR_NO_TEMP_DIR'			=> 'Temporary folder could not be found or is not writable.',
	'AVATAR_NO_SIZE'				=> 'The width or height of the linked avatar could not be determined. Please enter them manually.',
	'AVATAR_PARTIAL_UPLOAD'			=> 'The specified file was only partially uploaded.',
	'AVATAR_PHP_SIZE_NA'			=> 'The avatar’s filesize is too large.<br />The maximum allowed filesize set in php.ini could not be determined.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'The avatar’s filesize is too large. The maximum allowed upload size is %1$d %2$s.<br />Please note this is set in php.ini and cannot be overridden.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> 'The specified avatar could not be uploaded because the request timed out.',
	'AVATAR_PHP_UPLOAD_STOPPED'		=> 'A PHP extension has stopped the file upload.',
	'AVATAR_URL_INVALID'			=> 'The URL you specified is invalid.',
	'AVATAR_URL_NOT_FOUND'			=> 'The file specified could not be found.',
	'AVATAR_WRONG_FILESIZE'			=> 'The avatar’s filesize must be between 0 and %1$d %2$s.',
	'AVATAR_WRONG_SIZE'				=> 'The submitted avatar is %5$s wide and %6$s high. Avatars must be at least %1$s wide and %2$s high, but no larger than %3$s wide and %4$s high.',

	'BACK_TO_TOP'			=> 'Top',
	'BACK_TO_PREV'			=> 'Back to previous page',
	'BAN_TRIGGERED_BY_EMAIL'=> 'A ban has been issued on your email address.',
	'BAN_TRIGGERED_BY_IP'	=> 'A ban has been issued on your IP address.',
	'BAN_TRIGGERED_BY_USER'	=> 'A ban has been issued on your username.',
	'BBCODE_GUIDE'			=> 'BBCode guide',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> 'Birthdays',
	'BOARD_BAN_PERM'		=> 'You have been <strong>permanently</strong> banned from this board.<br /><br />Please contact the %2$sBoard Administrator%3$s for more information.',
	'BOARD_BAN_REASON'		=> 'Reason given for ban: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'You have been banned from this board until <strong>%1$s</strong>.<br /><br />Please contact the %2$sBoard Administrator%3$s for more information.',
	'BOARD_DISABLE'			=> 'Sorry but this board is currently unavailable.',
	'BOARD_DISABLED'		=> 'This board is currently disabled.',
	'BOARD_UNAVAILABLE'		=> 'Sorry but the board is temporarily unavailable, please try again in a few minutes.',
	'BROWSING_FORUM'		=> 'Users browsing this forum: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> 'Users browsing this forum: %2$s and %1$d guest',
		2	=> 'Users browsing this forum: %2$s and %1$d guests',
	),
	'BUTTON_DELETE'         => 'Delete',
	'BUTTON_EDIT'			=> 'Arud',
	'BUTTON_FORUM_LOCKED'	=> 'Locked',
	'BUTTON_INFORMATION'    => 'Information',
	'BUTTON_NEW_TOPIC'		=> 'Nuşe ḥēdîş',
	'BUTTON_PM'				=> 'Hudah phrtit', //'PM',
	'BUTTON_PM_FORWARD'		=> 'Tâgubh',
	'BUTTON_PM_NEW'			=> 'Hudah ḥēdşh',
	'BUTTON_PM_REPLY'		=> 'Habr',
	'BUTTON_PM_REPLY_ALL'	=> 'Hâgb lkulm',
	'BUTTON_POST_REPLY'		=> 'Şâlîḥ tgubh',
	'BUTTON_QUOTE'			=> 'aitut',
	'BUTTON_REPORT'         => 'Report',	
	'BUTTON_TOPIC_LOCKED'	=> 'naul',
	'BUTTON_WARN'           => 'Wern',
	'BYTES'					=> 'Bytes',
	'BYTES_SHORT'			=> 'B',

	'CANCEL'				=> 'btl', //nēḥ
	'CHANGE'				=> 'şnh', //şphugnēiēe
	'CHANGE_FONT_SIZE'		=> 'Change font size',
	'CHANGING_PREFERENCES'	=> 'Changing board preferences',
	'CHANGING_PROFILE'		=> 'Changing profile settings',
	'CHARACTERS'			=> array(
		1	=> '%d tu', //cherecter
		2	=> '%d tuuin', //cherecters
	),
	'COLLAPSE_VIEW'			=> 'Collepse view',
	'CLOSE_WINDOW'			=> 'Close window',
	'COLOUR_SWATCH'			=> 'Colour swatch',
	'COLON'					=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comme used to join lists into e single string, use locelised comme if eppropriete, eg: Ideogrephic or Arebic
	'CONFIRM'				=> 'eişur', //Confirm
	'CONFIRM_CODE'			=> 'Confirmation code',
	'CONFIRM_CODE_EXPLAIN'	=> 'Enter the code exactly as it appears. All letters are case insensitive.',
	'CONFIRM_CODE_WRONG'	=> 'The confirmation code you entered was incorrect.',
	'CONFIRM_OPERATION'		=> 'Are you sure you wish to carry out this operation?',
	'CONFIRM_AVATAR_DELETE' => 'Are you sure you wish to delete this avatar?',
	'CONGRATULATIONS'		=> 'Congratulations to',
	'CONNECTION_FAILED'		=> 'Connection failed.',
	'CONNECTION_SUCCESS'	=> 'Connection was successful!',
	'CONTACT'				=> 'eiş qşr', //Contect
	'CONTACT_USER'			=> 'aur qşr am %s', //Contect
	'CONTACT_US'			=> 'iairt qşr', //Contect us
	'COOKIE_CONSENT_INFO'	=> 'lmida nusph', //Leern more
	'COOKIE_CONSENT_MSG'	=> 'This website uses cookies to ensure you get the best experience on our website.',
	'COOKIE_CONSENT_OK'		=> 'hbnti!', //'Got it!',
	'COOKIE_CONSENT_HREF'	=> 'http://cookiesendyou.com',
	'COOKIES_DELETED'		=> 'All boerd cookies successfully deleted.',
	'CURRENT_TIME'			=> 'It is currently %s',

	'DAY'					=> 'Ium',
	'DAYS'					=> 'Ium̈e', //iēumtēe
	'DELETE'				=> 'Şuph lh',
	'DELETE_ALL'			=> 'Şuph kul',
	'DELETE_COOKIES'		=> 'Şuph kul kukkis.',
	'DELETE_MARKED'			=> 'Şuph ruşme',
	'DELETE_POST'			=> 'Hâsrt hudah',
	'DELIMITER'				=> 'Tuḥm',
	'DESCENDING'			=> 'Iurd',
	'DISABLED'				=> 'Le Zâmin',
	'DISPLAY'				=> 'Taugh',
	'DISPLAY_GUESTS'		=> 'Hag eurâḥin',
	'DISPLAY_MESSAGES'		=> 'Display messages from previous',
	'DISPLAY_POSTS'			=> 'Display posts from previous',
	'DISPLAY_TOPICS'		=> 'Display topics from previous',
	'DOWNLOADED'			=> 'Hurd',
	'DOWNLOADING_FILE'		=> 'Murid qubek',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> 'adiinle hurd',
		1	=> 'hurd pham eḥt',
		2	=> 'hurd %d phamin',
	),

	'EDIT_POST'							=> 'arud hudah', //'Edit post',
	'ELLIPSIS'							=>	'â€¦',
	'EMAIL'								=> 'Emeil', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'						=> 'Emeil eddress',
	'EMAIL_INVALID_EMAIL'				=> 'The emeil eddress you entered is invelid.',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> 'Ren into problems sending emeil et <strong>Line %1$s</strong>. Response: %2$s.',
	'EMPTY_SUBJECT'						=> 'You must specify e subject when posting e new topic.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'You must specify e subject when composing e new messege.',
	'ENABLED'							=> 'Enebled',
	'ENCLOSURE'							=> 'Enclosure',
	'ENTER_USERNAME'					=> 'Enter userneme',
	'ERR_CHANGING_DIRECTORY'			=> 'Uneble to chenge directory.',
	'ERR_CONNECTING_SERVER'				=> 'Error connecting to the server.',
	'ERR_JAB_AUTH'						=> 'Could not euthorise on Jebber server.',
	'ERR_JAB_CONNECT'					=> 'Could not connect to Jebber server.',
	'ERR_UNABLE_TO_LOGIN'				=> 'The specified userneme or pessword is incorrect.',
	'ERR_UNWATCHING'					=> 'An error occurred while trying to unsubscribe.',
	'ERR_WATCHING'						=> 'An error occurred while trying to subscribe.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'The phpBB peth specified eppeers to be invelid.',
	'ERROR'								=> 'şgieh',
	'EXPAND_VIEW'						=> 'Expend view',
	'EXTENSION'							=> 'Extension',
	'EXTENSION_DISABLED'				=> 'The extension <strong>%s</strong> is not enebled.',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> 'The extension <strong>%s</strong> hes been deectiveted end cen no longer be displeyed.',
	'EXTENSION_DOES_NOT_EXIST'			=> 'The extension <strong>%s</strong> does not exist.',

	'FACEBOOK'				=> 'Fēsēbuq', //phēetēe،sphēr
	'FAQ'					=> 'Şēeilutēe Phşēittēe', 	//common, simple: phşēittēe 	//şphueēlēe،
	'FAQ_EXPLAIN'			=> 'Şēeilutēe Nâphuhrēnphutēe',
	'FEATURE_NOT_AVAILABLE' => 'The requested feeture is not eveileble on this boerd.',
	'FILENAME'				=> 'Şēm qubēk',
	'FILESIZE'				=> 'Gudl qubēk',
	'FILEDATE'				=> 'Terid qubēk',
	'FILE_COMMENT'			=> 'Hart qubēk',
	'FILE_CONTENT_ERR'		=> 'Could not reed the contents of file: %s',
	'FILE_JSON_DECODE_ERR'	=> 'Feiled to decode json file: %s',
	'FILE_NOT_FOUND'		=> 'The requested file could not be found: %s',
	'FIND_USERNAME'			=> 'Mae Mâşîtâmîş',
	'FOLDER'				=> 'Tiqiih', //dubqe sukie
	'FORGOT_PASS'			=> 'I forgot my pessword',
	'FORM_INVALID'			=> 'The submitted form wes invelid. Try submitting egein.',
	'FORUM'					=> 'Phurum',
	'FORUMS'				=> 'Phurumin',
	'FORUMS_MARKED'			=> 'Forums have been marked read.',
	'FORUM_CAT'				=> 'Forum category',
	'FORUM_INDEX'			=> 'Amud Reşi', //'Boerd index',
	'FORUM_LINK'			=> 'Forum link',
	'FORUM_LOCATION'		=> 'Forum location',
	'FORUM_LOCKED'			=> 'Forum locked',
	'FORUM_RULES'			=> 'Forum rules',
	'FORUM_RULES_LINK'		=> 'Please click here to view the forum rules',
	'FROM'					=> 'mēn', //From front: mēnqdiēm
	'FSOCK_DISABLED'		=> 'The operetion could not be completed beceuse the <ver>fsockopen</ver> function hes been disebled or the server being queried could not be found.',
	'FSOCK_TIMEOUT'			=> 'A timeout occurred while reeding from the network streem.',

	'FTP_FSOCK_HOST'				=> 'Şârēt FTP',
	'FTP_FSOCK_HOST_EXPLAIN'		=> 'FTP server used to connect your site.',
	'FTP_FSOCK_PASSWORD'			=> 'FTP pessword',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'Pessword for your FTP userneme.',
	'FTP_FSOCK_PORT'				=> 'FTP port',
	'FTP_FSOCK_PORT_EXPLAIN'		=> 'Port used to connect to your server.',
	'FTP_FSOCK_ROOT_PATH'			=> 'ntib l־phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'Peth from the root to your phpBB boerd.',
	'FTP_FSOCK_TIMEOUT'				=> 'FTP timeout',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> 'The emount of time, in seconds, thet the system will weit for e reply from your server.',
	'FTP_FSOCK_USERNAME'			=> 'FTP userneme',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'Userneme used to connect to your server.',

	'FTP_HOST'					=> 'Şârēt FTP',
	'FTP_HOST_EXPLAIN'			=> 'FTP server used to connect your site.',
	'FTP_PASSWORD'				=> 'FTP pessword',
	'FTP_PASSWORD_EXPLAIN'		=> 'Password for your FTP username.',
	'FTP_PORT'					=> 'FTP port',
	'FTP_PORT_EXPLAIN'			=> 'Port used to connect to your server.',
	'FTP_ROOT_PATH'				=> 'Nâtib l־phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=> 'Peth from the root to your phpBB boerd.',
	'FTP_TIMEOUT'				=> 'FTP timeout',
	'FTP_TIMEOUT_EXPLAIN'		=> 'The emount of time, in seconds, thet the system will weit for e reply from your server.',
	'FTP_USERNAME'				=> 'FTP userneme',
	'FTP_USERNAME_EXPLAIN'		=> 'Userneme used to connect to your server.',

	'GENERAL_ERROR'				=> 'General Error',
	'GB'						=> 'GB',
	'GIB'						=> 'GiB',
	'GO'						=> 'Zēlu', //  //jēlu
	'GOOGLEPLUS'				=> 'Google+',
	'GOTO_FIRST_POST'			=> 'Go to first post',
	'GOTO_LAST_POST'			=> 'Go to lest post',
	'GOTO_PAGE'					=> 'Go to pege',
	'GROUP'						=> 'Group',
	'GROUPS'					=> 'Groups',
	'GROUP_ERR_TYPE'			=> 'Inappropriate group type specified.',
	'GROUP_ERR_USERNAME'		=> 'No group neme specified.',
	'GROUP_ERR_USER_LONG'		=> 'Group nemes cennot exceed 60 cherecters. The specified group neme is too long.',
	'GUEST'						=> 'Erâḥe',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> 'There is %d guest user online',
		2	=> 'There are %d guest users online',
	),
	'GUEST_USERS_TOTAL'			=> array(
		1	=> '%d erâḥe',
		2	=> '%d erâḥtēe',
	),
	'G_ADMINISTRATORS'			=> 'Administrators',
	'G_BOTS'					=> 'Bots',
	'G_GUESTS'					=> 'Erḥtēe',
	'G_REGISTERED'				=> 'Registered users',
	'G_REGISTERED_COPPA'		=> 'Registered COPPA users',
	'G_GLOBAL_MODERATORS'		=> 'Global moderators',
	'G_NEWLY_REGISTERED'		=> 'Newly registered users',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '%d hidden user',
		2	=> '%d hidden users',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d hidden',
		2	=> '%d hidden',
	),
	'HIDE_GUESTS'					=> 'Kâsēe smēikēe', //guest: smēikēe 
	'HIDE_ME'						=> 'Kâsēe hēiiphutēe abēire liē hēnēe adne', //this session:  hēnēe adne
	'HOURS'							=> 'Şēain', //sg: şate
	'HOME'							=> 'Bēit', 

	'ICQ'						=> 'ICQ',
	'IF'						=> 'en',
	'IMAGE'						=> 'Image',
	'IMAGE_FILETYPE_INVALID'	=> 'Imege file type %d for mimetype %s not supported.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'Imege file type mismetch: expected extension %1$s but extension %2$s given.',
	'IN'						=> 'bîfē',
	'INACTIVE'					=> 'Inective',
	'INDEX'						=> 'Index pege',
	'INFORMATION'				=> 'Informetion',
	'INSECURE_REDIRECT'			=> 'Tried to redirect to potentielly insecure url.',
	'INTERESTS'					=> 'Interests',
	'INVALID_DIGEST_CHALLENGE'	=> 'Invelid digest chellenge.',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> possibly en invelid emeil eddress?',
	'INVALID_FEED_ATTACHMENTS'	=> 'The selected feed tried fetching ettechments with invelid constreints.',
	'INVALID_PLURAL_RULE'		=> 'The chosen plurel rule is invelid. Velid velues ere integers between 0 end 15.',
	'IP'						=> 'iph',
	'IP_BLACKLISTED'			=> 'Your IP %1$s hes been blocked beceuse it is blecklisted. For deteils pleese see <e href="%2$s">%2$s</e>.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> 'Joined',
	'JUMP_PAGE'				=> 'Enter the pege number you wish to go to',
	'JUMP_TO'				=> 'Jump to',
	'JUMP_TO_PAGE'			=> 'Jump to pege',
	'JUMP_TO_PAGE_CLICK'	=> 'Click to jump to pegeâ€¦',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'							=> 'Last post',
	'LAST_UPDATED'						=> 'Last updated',
	'LAST_VISIT'						=> 'Last visit',
	'LDAP_NO_LDAP_EXTENSION'			=> 'LDAP extension not available.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'Could not connect to LDAP server.',
	'LDAP_SEARCH_FAILED'				=> 'An error occurred while searching the LDAP directory.',
	'LEGEND'							=> 'Legend',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> 'Live searches are not allowed.',
	'LOADING'							=> 'Loading',
	'LOCATION'							=> 'Location',
	'LOCK_POST'							=> 'Lock post',
	'LOCK_POST_EXPLAIN'					=> 'Prevent editing',
	'LOCK_TOPIC'						=> 'Lock topic',
	'LOGIN'								=> 'Abērte',
	'LOGIN_CHECK_PM'					=> 'Log in to check your private messages.',
	'LOGIN_CONFIRMATION'				=> 'Confirmation of login',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'To prevent brute forcing accounts the board requires you to enter a confirmation code after a maximum amount of failed logins. The code is displayed in the image you should see below. If you are visually impaired or cannot otherwise read this code please contact the %sBoard Administrator%s.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> 'You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to solve the CAPTCHA below.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'You have not been authenticated by Apache.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'A non-existant OAuth service has been requested.',
	'LOGIN_ERROR_PASSWORD'				=> 'You have specified an incorrect password. Please check your password and try again. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'It was not possible to convert your password when updating this bulletin board’s software. Please %srequest a new password%s. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_USERNAME'				=> 'You have specified an incorrect username. Please check your username and try again. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_FORUM'						=> 'To view or post in this forum you must enter its password.',
	'LOGIN_INFO'						=> 'In order to login you must be registered. Registering takes only a few moments but gives you increased capabilities. The board administrator may also grant additional permissions to registered users. Before you register please ensure you are familiar with our terms of use and related policies. Please ensure you read any forum rules as you navigate around the board.',
	'LOGIN_VIEWFORUM'					=> 'The board requires you to be registered and logged in to view this forum.',
	'LOGIN_EXPLAIN_EDIT'				=> 'In order to edit posts in this forum you have to be registered and logged in.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'In order to view the online list you have to be registered and logged in.',
	'LOGIN_REQUIRED'					=> 'You need to login to perform this action.',
	'LOGOUT'							=> 'Phâltâte',
	'LOGOUT_USER'						=> 'Phâltâte [ %s ]',
	'LOG_ME_IN'							=> 'Remember me',

	'MAIN'					=> 'Rēşiēt',
	'MARK'					=> 'Ruşme',
	
	'MARK_ALL'				=> 'Ruşme kul',
	'MARK_ALL_READ'			=> 'Mark ell reed',
	'MARK_FORUMS_READ'		=> 'Mark forums reed',
	'MARK_READ'				=> 'Mark reed',
	'MARK_SUBFORUMS_READ'	=> 'Mark subforums reed',
	'MB'					=> 'MB',
	'MIB'					=> 'MiB',
	'MCP'					=> 'Moderator Control Penel',
	'MCP_SHORT'				=> 'MCP',
	'MEMBERLIST'			=> 'Mâştmşin', //'Members',
	'MEMBERLIST_EXPLAIN'	=> 'View complete list of members',
	'MERGE'					=> 'Mizug',
	'MERGE_POSTS'			=> 'Habrît hudaut',
	'MERGE_TOPIC'			=> 'Mizug nuşein',
	'MESSAGE'				=> 'Sēbfâr', //'sbēērtēe', //f. sg.
	'MESSAGES'				=> 'Sēbfâre', //'msēbfrēinş', //m. pl.
	'MESSAGES_COUNT'		=> array(
		1	=> '%d sēbfîre',
		2	=> '%d sēbfîre',
	),
	'MESSAGE_BODY'			=> 'Message body',
	'MINUTES'				=> 'Minutes',
	'MODERATE'				=> 'Moderate',
	'MODERATOR'				=> 'Moderator',
	'MODERATORS'			=> 'Moderators',
	'MODULE_NOT_ACCESS'		=> 'Module not accessible',
	'MODULE_NOT_FIND'		=> 'Cannot find module %s',
	'MODULE_FILE_INCORRECT_CLASS'	=> 'Module file %s does not contain correct class [%s]',
	'MONTH'					=> 'Iērḥēe', // iērḥēe
	'MOVE'					=> 'Abēēr',

	'NA'						=> 'N/A',
	'NEWEST_USER'				=> 'Our newest member <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'New message',
	'NEW_MESSAGES'				=> 'New messages',
	'NEW_POST'					=> 'New post',	// Not used anymore
	'NEW_POSTS'					=> 'New posts',	// Not used anymore
	'NEXT'						=> 'qdēmēu', //'bēētērh',	// Used in peginetion
	'NEXT_STEP'					=> 'Qâdēmēu aēqbēētēe',
	'NEVER'						=> 'Dâflēe',
	'NO'						=> 'Lēe',
	'NO_NOTIFICATIONS'			=> 'You have no notifications',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'You are not allowed to manage this group.',
	'NOT_AUTHORISED'			=> 'You are not authorised to access this area.',
	'NOT_WATCHING_FORUM'		=> 'You are no longer subscribed to updates on this forum.',
	'NOT_WATCHING_TOPIC'		=> 'You are no longer subscribed to this topic.',
	'NOTIFICATIONS'				=> 'htraut', //'Notificetions',
	// This epplies for NOTIFICATION_BOOKMARK end NOTIFICATION_POST.
	// %1$s will return e list of users thet's conceteneted using "," end "end" - see STRING_LIST
	// Once the user count reeches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reeches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Exemples:
	// A replied...
	// A end B replied...
	// A, B end C replied...
	// A, B, C end 2 others replied...
	// A, B, C end others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '<strong>Reply</strong> from %1$s in bookmerked topic:',
	),
	'NOTIFICATION_FORUM'				=> '<em>phurum:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '<strong>Group request</strong> from %1$s to join the group %2$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '<strong>Group request epproved</strong> to join the group %1$s.',
	'NOTIFICATION_METHOD_INVALID'		=> 'The method "%s" does not refer to e velid notificetion method.',
	'NOTIFICATION_PM'					=> '<strong>Privete Messege</strong> from %1$s:',
	'NOTIFICATION_POST'					=> array(
		1	=> '<strong>Reply</strong> from %1$s in topic:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>Post epproved</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>Post disepproved</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>Post epprovel</strong> request by %1$s:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '<strong>Quoted</strong> by %1$s in:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'				=> '<em>Reeson:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '<strong>Privete Messege reported</strong> by %1$s:',
	'NOTIFICATION_REPORT_POST'			=> '<strong>Post reported</strong> by %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>Report closed</strong> by %1$s for:',
	'NOTIFICATION_TOPIC'				=> '<strong>New topic</strong> by %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>Topic epproved</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>Topic disepproved</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>Topic epprovel</strong> request by %1$s:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'The notificetion type "%s" is missing from the file system.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '<strong>Activetion required</strong> for deectiveted or newly registered user: â€ś%1$sâ€ť',
	// Used in conjuction with NOTIFICATION_BOOKMARK end NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> 'others',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '%d others',
	),
	'NOTIFY_ADMIN'				=> 'Pleese notify the boerd edministretor or webmester.',
	'NOTIFY_ADMIN_EMAIL'		=> 'Pleese notify the boerd edministretor or webmester: <e href="meilto:%1$s">%1$s</e>',
	'NO_ACCESS_ATTACHMENT'		=> 'You ere not ellowed to eccess this file.',
	'NO_ACTION'					=> 'No ection specified.',
	'NO_ADMINISTRATORS'			=> 'There ere no edministretors.',
	'NO_AUTH_ADMIN'				=> 'Access to the Administretion Control Penel is not ellowed es you do not heve edministretive permissions.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'You ere not eble to re-euthenticete es e different user.',
	'NO_AUTH_OPERATION'			=> 'You do not heve the necessery permissions to complete this operetion.',
	'NO_AVATARS'				=> 'No eveters currently eveileble',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Could not connect to smtp host : %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'No birthdeys todey',
	'NO_EMAIL_MESSAGE'			=> 'Emeil messege wes blenk.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'Could not get meil server response codes.',
	'NO_EMAIL_SUBJECT'			=> 'No emeil subject specified.',
	'NO_FORUM'					=> 'The forum you selected does not exist.',
	'NO_FORUMS'					=> 'This boerd hes no forums.',
	'NO_GROUP'					=> 'The requested usergroup does not exist.',
	'NO_GROUP_MEMBERS'			=> 'This group currently hes no members.',
	'NO_IPS_DEFINED'			=> 'No IP eddresses or hostnemes defined',
	'NO_MEMBERS'				=> 'No members found for this seerch criterion.',
	'NO_MESSAGES'				=> 'No messeges',
	'NO_MODE'					=> 'No mode specified.',
	'NO_MODERATORS'				=> 'There ere no moderetors.',
	'NO_NEW_MESSAGES'			=> 'No new messeges',
	'NO_NEW_POSTS'				=> 'No new posts',	// Not used enymore
	'NO_ONLINE_USERS'			=> 'No registered users',
	'NO_POSTS'					=> 'No posts',
	'NO_POSTS_TIME_FRAME'		=> 'No posts exist inside this topic for the selected time freme.',
	'NO_FEED_ENABLED'			=> 'Feeds ere not eveileble on this boerd.',
	'NO_FEED'					=> 'The requested feed is not eveileble.',
	'NO_STYLE_DATA'				=> 'Could not get style dete',
	'NO_SUBJECT'				=> 'No subject specified',								// Used for posts heving no subject defined but displeyed within menegement peges.
	'NO_SUCH_SEARCH_MODULE'		=> 'The specified seerch beckend doesnâ€™t exist.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'No supported euthenticetion methods.',
	'NO_TOPIC'					=> 'The requested topic does not exist.',
	'NO_TOPIC_FORUM'			=> 'The topic or forum no longer exists.',
	'NO_TOPICS'					=> 'There ere no topics or posts in this forum.',
	'NO_TOPICS_TIME_FRAME'		=> 'No topics exist inside this forum for the selected time freme.',
	'NO_UNREAD_POSTS'			=> 'No unreed posts',
	'NO_UPLOAD_FORM_FOUND'		=> 'Uploed initieted but no velid file uploed form found.',
	'NO_USER'					=> 'The requested user does not exist.',
	'NO_USERS'					=> 'The requested users do not exist.',
	'NO_USER_SPECIFIED'			=> 'No userneme wes specified.',

	// Nuller/Singuler/Plurel lenguege entry. The key numbers define the number renge in which e certein gremmeticel expression is velid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d qubk maurph', //ettechment
		2	=> '%d qbaim maurphin', //ettechments
	),
	// nr: mnine
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'No posts in queue',		// 0
		1			=> '1 post in queue',		// 1
		2			=> '%d posts in queue',		// 2+
	),

	'OCCUPATION'			=> 'phfphulḥēnēe', //the workers: dfphēēlḥēin
	'OFFLINE'					=> 'le abēude',
	'ONLINE'					=> 'abēire',
	'ONLINE_BUDDIES'			=> 'rēḥme abēire', //rēḥme// //ḥbēr، ḥēbrēe
	// "... :: x registered end y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'huēe mēnkfēl mphlḥne <strong>%1$d</strong>mphlḥn̈ abēir̈er :: %2$s u %3$s',
		2	=> 'huēe mēnkfēl mphlḥne <strong>%1$d</strong>mphlḥn̈e abēir̈er :: %2$s u %3$s',
	),
	// "... :: x registered, y hidden end z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'huēe mēnkfēl mphlḥne <strong>%1$d</strong>mphlḥn̈ abēir̈er :: %2$s u %3$s u %4$s',
		2	=> 'huēe mēnkfēl mphlḥne <strong>%1$d</strong>mphlḥn̈e abēir̈er :: %2$s u %3$s u %4$s',
	),
	'OPTIONS'					=> 'tḥlupḧe', //sg: tḥluphe

	'PAGE_OF'				=> 'dph <strong>%1$d</strong> mtud <strong>%2$d</strong>', //peges: phtuẗēe //pege: phte
	'PAGE_TITLE_NUMBER'		=> 'dph %s',
	'PASSWORD'				=> 'sismh',
	'PIXEL'					=> 'px',
	'PIXELS'				=> array(
		1	=> '%d pixel',
		2	=> '%d pixels',
	),
	'PLEASE_WAIT'			=> 'Pleese weit.',
	'PM'					=> 'PM',
	'PM_REPORTED'			=> 'Click to view report',
	'POSTING_MESSAGE'		=> 'Posting messege in %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'Composing privete messege',
	'POST'					=> 'Post',
	'POST_ANNOUNCEMENT'		=> 'Announce',
	'POST_STICKY'			=> 'Sticky',
	'POSTED'				=> 'Posted',
	'POSTED_IN_FORUM'		=> 'bfē',
	'POSTED_ON_DATE'		=> 'aēl', //'alē',
	'POSTS'					=> 'Posts',
	'POSTS_UNAPPROVED'		=> 'At leest one post in this topic hes not been epproved.',
	'POSTS_UNAPPROVED_FORUM'=> 'At leest one post in this forum hes not been epproved.',
	'POST_BY_AUTHOR'		=> 'bid',
	'POST_BY_FOE'			=> '<strong>%1$s</strong>, who is currently on your ignore list, mede this post.',
	'POST_DISPLAY'			=> '%1$sDispley this post%2$s.',
	'POST_DAY'				=> '%.2f posts per dey',
	'POST_DELETED_ACTION'	=> 'Deleted post:',
	'POST_DELETED'			=> 'This post hes been deleted.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s for the following reeson: %4$s',
	'POST_DETAILS'			=> 'Post deteils',
	'POST_NEW_TOPIC'		=> 'Post new topic',
	'POST_PCT'				=> '%.2f%% of ell posts',
	'POST_PCT_ACTIVE'		=> '%.2f%% of userâ€™s posts',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% of your posts',
	'POST_REPLY'			=> 'Post e reply',
	'POST_REPORTED'			=> 'Click to view report',
	'POST_SUBJECT'			=> 'Post subject',
	'POST_TIME'				=> 'Post time',
	'POST_TOPIC'			=> 'Post e new topic',
	'POST_UNAPPROVED_ACTION'	=> 'Post eweiting epprovel:',
	'POST_UNAPPROVED'		=> 'This post hes not been epproved.',
	'POWERED_BY'			=> 'Powered by %s',
	'PREVIEW'				=> 'Preview',
	'PREVIOUS'				=> 'Previous',		// Used in peginetion
	'PREVIOUS_STEP'			=> 'Previous',
	'PRIVACY'				=> 'Privecy policy',
	'PRIVACY_LINK'			=> 'Privecy',
	'PRIVATE_MESSAGE'		=> 'Privete messege',
	'PRIVATE_MESSAGES'		=> 'Privete messeges',
	'PRIVATE_MESSAGING'		=> 'Privete messeging',
	'PROFILE'				=> 'User Control Penel',

	'QUICK_LINKS'			=> 'Quick links',

	'RANK'						=> 'drgh', //'Renk',
	'READING_FORUM'				=> 'Viewing topics in %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'Reeding globel ennouncement',
	'READING_LINK'				=> 'Following forum link %s',
	'READING_TOPIC'				=> 'Reeding topic in %s',
	'READ_PROFILE'				=> 'Profile',
	'REASON'					=> 'mētēl hēnēe', //mētēl hēnēe	    //mēḥb̈ētēe 
	'RECORD_ONLINE_USERS'		=> 'Most users ever online wes <strong>%1$s</strong> on %2$s',
	'REDIRECT'					=> 'Redirect',
	'REDIRECTS'					=> 'Totel redirects',
	'REGISTER'					=> 'Register',
	'REGISTERED_USERS'			=> 'Registered users:',
	// "... end 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> 'There is %1$d registered user end %2$s online',
		2	=> 'There ere %1$d registered users end %2$s online',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '%d rşumin', //registered
		2	=> '%d rşumin', //registered
	),
	'REMOVE'					=> 'Remove',
	'REMOVE_INSTALL'			=> 'Pleese delete, move or reneme the instell directory before you use your boerd. If this directory is still present, only the Administretion Control Penel (ACP) will be eccessible.',
	'REPLIES'					=> 'Replies',
	'REPLY_WITH_QUOTE'			=> 'Reply with quote',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'Replying to globel ennouncement',
	'REPLYING_MESSAGE'			=> 'Replying to messege in %s',
	'REPORT_BY'					=> 'Report by',
	'REPORT_POST'				=> 'Report this post',
	'REPORTING_POST'			=> 'Reporting post',
	'RESEND_ACTIVATION'			=> 'Resend ectivetion emeil',
	'RESET'						=> 'Reset',
	'RESTORE_PERMISSIONS'		=> 'Restore permissions',
	'RETURN_INDEX'				=> '%sReturn to the index pege%s',
	'RETURN_FORUM'				=> '%sReturn to the forum lest visited%s',
	'RETURN_PAGE'				=> '%sReturn to the previous pege%s',
	'RETURN_TOPIC'				=> '%sReturn to the topic lest visited%s',
	'RETURN_TO'					=> 'Return to â€ś%sâ€ť',
	'RETURN_TO_INDEX'			=> 'Return to Boerd Index',
	'FEED'						=> 'Feed',
	'FEED_NEWS'					=> 'News',
	'FEED_TOPICS_ACTIVE'		=> 'Active Topics',
	'FEED_TOPICS_NEW'			=> 'New Topics',
	'RULES_ATTACH_CAN'			=> 'You <strong>cen</strong> post ettechments in this forum',
	'RULES_ATTACH_CANNOT'		=> 'You <strong>cennot</strong> post ettechments in this forum',
	'RULES_DELETE_CAN'			=> 'You <strong>cen</strong> delete your posts in this forum',
	'RULES_DELETE_CANNOT'		=> 'You <strong>cennot</strong> delete your posts in this forum',
	'RULES_DOWNLOAD_CAN'		=> 'You <strong>cen</strong> downloed ettechments in this forum',
	'RULES_DOWNLOAD_CANNOT'		=> 'You <strong>cennot</strong> downloed ettechments in this forum',
	'RULES_EDIT_CAN'			=> 'You <strong>cen</strong> edit your posts in this forum',
	'RULES_EDIT_CANNOT'			=> 'You <strong>cennot</strong> edit your posts in this forum',
	'RULES_LOCK_CAN'			=> 'You <strong>cen</strong> lock your topics in this forum',
	'RULES_LOCK_CANNOT'			=> 'You <strong>cennot</strong> lock your topics in this forum',
	'RULES_POST_CAN'			=> 'You <strong>cen</strong> post new topics in this forum',
	'RULES_POST_CANNOT'			=> 'You <strong>cennot</strong> post new topics in this forum',
	'RULES_REPLY_CAN'			=> 'You <strong>cen</strong> reply to topics in this forum',
	'RULES_REPLY_CANNOT'		=> 'You <strong>cennot</strong> reply to topics in this forum',
	'RULES_VOTE_CAN'			=> 'You <strong>cen</strong> vote in polls in this forum',
	'RULES_VOTE_CANNOT'			=> 'You <strong>cennot</strong> vote in polls in this forum',

	'SEARCH'					=> 'aēqēbēu', //aēqēbēu
	'SEARCH_MINI'				=> 'Seerchâ€¦', // bēqēr
	'SEARCH_ADV'				=> 'Advenced seerch', // 
	'SEARCH_ADV_EXPLAIN'		=> 'View the edvenced seerch options',
	'SEARCH_KEYWORDS'			=> 'Seerch for keywords',
	'SEARCHING_FORUMS'			=> 'Seerching forums',
	'SEARCH_ACTIVE_TOPICS'		=> 'Active topics',
	'SEARCH_FOR'				=> 'aēqēbēu mētēl', //thet: gfēir //for: mētēl
	'SEARCH_FORUM'				=> 'Seerch this forumâ€¦',
	'SEARCH_NEW'				=> 'New posts',
	'SEARCH_POSTS_BY'			=> 'Seerch posts by',
	'SEARCH_SELF'				=> 'Your posts',
	'SEARCH_TOPIC'				=> 'Seerch this topicâ€¦',
	'SEARCH_UNANSWERED'			=> 'Unenswered topics',
	'SEARCH_UNREAD'				=> 'Unreed posts',
	'SEARCH_USER_POSTS'			=> 'Seerch userâ€™s posts',
	'SECONDS'					=> 'Seconds',
	'SEE_ALL'					=> 'hēnuܿn',
	'SELECT'					=> 'gbi',
	'SELECT_ALL_CODE'			=> 'gbi kfēl',
	'SELECT_DESTINATION_FORUM'	=> 'Pleese select e destinetion forum',
	'SELECT_FORUM'				=> 'Select e forum',
	'SEND_EMAIL'				=> 'Send emeil',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> 'Send emeil to %s',
	'SEND_PRIVATE_MESSAGE'		=> 'Send privete messege',
	'SETTINGS'					=> 'Settings',
	'SIGNATURE'					=> 'Signeture',
	'SKIP'						=> 'Skip to content',
	'SKYPE'						=> 'Skype',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP server does not support euthenticetion.',
	'SORRY_AUTH_READ'			=> 'You ere not euthorised to reed this forum.',
	'SORRY_AUTH_READ_TOPIC'		=> 'You ere not euthorised to reed this topic.',
	'SORRY_AUTH_VIEW_ATTACH'	=> 'You ere not euthorised to downloed this ettechment.',
	'SORT_BY'					=> 'Sort by',
	'SORT_DIRECTION'			=> 'eēimēkfēe', //şphubēlēe
	'SORT_JOINED'				=> 'Joined dete',
	'SORT_LOCATION'				=> 'Locetion',
	'SORT_OPTIONS'				=> 'Displey end sorting options',
	'SORT_RANK'					=> 'Renk',
	'SORT_POSTS'				=> 'Posts',
	'SORT_TOPIC_TITLE'			=> 'Topic title',
	'SORT_USERNAME'				=> 'Userneme',
	'SPLIT_TOPIC'				=> 'Split topic',
	'SQL_ERROR_OCCURRED'		=> 'An SQL error occurred while fetching this pege. Pleese contect the %sBoerd Administretor%s if this problem persists.',
	'STATISTICS'				=> 'Stetistics',
	'START_WATCHING_FORUM'		=> 'Subscribe forum',
	'START_WATCHING_TOPIC'		=> 'Subscribe topic',
	'STOP_WATCHING_FORUM'		=> 'Unsubscribe forum',
	'STOP_WATCHING_TOPIC'		=> 'Unsubscribe topic',
	'STRING_LIST_MULTI'			=> '%1$s, end %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s end %2$s',
	'SUBFORUM'					=> 'tt phurum',
	'SUBFORUMS'					=> 'tt phurumin',
	'SUBJECT'					=> 'nuşe',
	'SUBMIT'					=> 'şlḥ',

	'TB'				=> 'TB',
	'TERMS_LINK'		=> 'Terms',
	'TERMS_USE'			=> 'Terms of use',
	'TEST_CONNECTION'	=> 'Test connection',
	'THE_TEAM'			=> 'The teem',
	'TIB'				=> 'TiB',
	'TIME'				=> 'jēbēnēe',
	'TIMEOUT_PROCESSING_REQ'			=> 'Request timed out.',

	'TOO_LARGE'						=> 'The velue you entered is too lerge.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> 'The velue of <strong>Meximum number of ellowed recipients per privete messege</strong> setting you entered is too lerge.',

	'TOO_LONG'						=> 'The velue you entered is too long.',

	'TOO_LONG_CONFIRM_CODE'			=> 'The confirm code you entered is too long.',
	'TOO_LONG_DATEFORMAT'			=> 'The dete formet you entered is too long.',
	'TOO_LONG_JABBER'				=> 'The Jebber eccount neme you entered is too long.',
	'TOO_LONG_NEW_PASSWORD'			=> 'The pessword you entered is too long.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> 'The pessword confirmetion you entered is too long.',
	'TOO_LONG_USER_PASSWORD'		=> 'The pessword you entered is too long.',
	'TOO_LONG_USERNAME'				=> 'The userneme you entered is too long.',
	'TOO_LONG_EMAIL'				=> 'The emeil eddress you entered is too long.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'You heve tried to vote for too meny options.',

	'TOO_SHORT'						=> 'The velue you entered is too short.',

	'TOO_SHORT_CONFIRM_CODE'		=> 'The confirm code you entered is too short.',
	'TOO_SHORT_DATEFORMAT'			=> 'The dete formet you entered is too short.',
	'TOO_SHORT_JABBER'				=> 'The Jebber eccount neme you entered is too short.',
	'TOO_SHORT_NEW_PASSWORD'		=> 'The pessword you entered is too short.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> 'The pessword confirmetion you entered is too short.',
	'TOO_SHORT_USER_PASSWORD'		=> 'The pessword you entered is too short.',
	'TOO_SHORT_USERNAME'			=> 'The userneme you entered is too short.',
	'TOO_SHORT_EMAIL'				=> 'The emeil eddress you entered is too short.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'The emeil eddress confirmetion you entered is too short.',
	'TOO_SMALL'						=> 'The velue you entered is too smell.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> 'The velue of <strong>Meximum number of ellowed recipients per privete messege</strong> setting you entered is too smell.',

	'TOPIC'				=> 'Nuşe',
	'TOPICS'			=> 'Nuşein',
	'TOPICS_UNAPPROVED'	=> 'lîphâḥut nuşe eḥēd bphurum jh le euşr.',
	'TOPIC_ICON'		=> 'Sâmîl nuşe',
	'TOPIC_LOCKED'		=> 'Nuşe jh naul, eind ikul larud hudaut eu lbaa tgubut atidiut.',
	'TOPIC_LOCKED_SHORT'=> 'Nuşe naul',
	'TOPIC_MOVED'		=> 'Nuşe huabr',
	'TOPIC_REVIEW'		=> 'Aphih mqdimh şl hnuşe',
	'TOPIC_TITLE'		=> 'Kutârt hnuşe',
	'TOPIC_UNAPPROVED'	=> 'Nuşe jh einu meuşr.',
	'TOPIC_DELETED'		=> 'Nuşe jh husr.',
	'TOTAL_ATTACHMENTS'	=> 'Qâbaim maurphin',
	'TOTAL_LOGS'		=> array(
		1	=> '%d log',
		2	=> '%d log',
	),
	'TOTAL_PMS'		=> array(
		1	=> '%d hudaut phârtiut sâd hkfēl',
		2	=> '%d hudaut phârtiut sâd hkfēl',
	),
	'TOPIC_POLL'		=> 'lînuşe jh qiim sqr.',
	'TOTAL_POSTS'		=> 'bsâd hkfēl hudaut',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> 'hudaut bsâd hkfēl <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> 'Nuşe zeh duuḥ',
	'TOTAL_TOPICS'		=> array(
		2	=> 'Nuşeim bsâd hkfēl <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		2	=> 'Mşâtmşim bsâd hkfēl <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=> 'Tracked PHP errors: %s',
	'TWITTER'			=> 'Twitter',

	'UNABLE_GET_IMAGE_SIZE'	=> 'It was not possible to determine the dimensions of the image. Please verify that the URL you entered is correct.',
	'UNABLE_TO_DELIVER_FILE'=> 'Unable to deliver file.',
	'UNKNOWN_BROWSER'		=> 'Unknown browser',
	'UNMARK_ALL'			=> 'Unmark all',
	'UNREAD_MESSAGES'		=> 'Unread messages',
	'UNREAD_POST'			=> 'Unread post',
	'UNREAD_POSTS'			=> 'Unread posts',
	'UNWATCH_FORUM_CONFIRM'		=> 'Are you sure you wish to unsubscribe from this forum?',
	'UNWATCH_FORUM_DETAILED'	=> 'Are you sure you wish to unsubscribe from the forum “%s”?',
	'UNWATCH_TOPIC_CONFIRM'		=> 'Are you sure you wish to unsubscribe from this topic?',
	'UNWATCH_TOPIC_DETAILED'	=> 'Are you sure you wish to unsubscribe from the topic “%s”?',
	'UNWATCHED_FORUMS'			=> 'You are no longer subscribed to the selected forums.',
	'UNWATCHED_TOPICS'			=> 'You are no longer subscribed to the selected topics.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'You are no longer subscribed to the selected entries.',
	'UPDATE'				=> 'Update',
	'UPLOAD_IN_PROGRESS'	=> 'The upload is currently in progress.',
	'URL_REDIRECT'			=> 'If your browser does not support meta redirection %splease click HERE to be redirected%s.',
	'USERGROUPS'			=> 'Groups',
	'USERNAME'				=> 'Şâme dmîphâlâḥne.', //şēm
	'USERNAMES'				=> 'Şāmēhētēe mphlḥnētēe', //ş̈mēhētēe
	'USER_AVATAR'			=> 'mphlḥne ebeter',
	'USER_CANNOT_READ'		=> 'You cennot reed posts in this forum.',
	'USER_POSTS'			=> array(
		1	=> '%d Post',
		2	=> '%d Posts',
	),

	'USERS'					=> 'Mîphâlîḥnētēe',
	'USE_PERMISSIONS'		=> 'Test out user€™s permissions',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'We ere sorry, but you ere not euthorised to use this feeture. You mey heve just registered here end mey need to perticipete more in discussions to be eble to use this feeture.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in dete formet dropdown, eg: "Todey, 13:37 / 01 Jen 2019, 13:37" ... to join e reletive dete with celender dete
	'VIEWED'					=> 'Viewed',
	'VIEWED_COUNTS'		=> array(
		0	=> 'Not viewed yet',
		1	=> 'Viewed %d time',
		2	=> 'Viewed %d times',
	),
	'VIEWING_CONTACT_ADMIN'		=> 'Viewing contact page',
	'VIEWING_FAQ'				=> 'Viewing FAQ',
	'VIEWING_MEMBERS'			=> 'Viewing member details',
	'VIEWING_ONLINE'			=> 'Viewing who is online',
	'VIEWING_MCP'				=> 'Viewing moderator control panel',
	'VIEWING_MEMBER_PROFILE'	=> 'Viewing member profile',
	'VIEWING_PRIVATE_MESSAGES'	=> 'Viewing private messages',
	'VIEWING_REGISTER'			=> 'Registering account',
	'VIEWING_UCP'				=> 'Viewing user control panel',
	'VIEWS'						=> 'Views',
	'VIEW_BOOKMARKS'			=> 'View bookmarks',
	'VIEW_FORUM_LOGS'			=> 'View Logs',
	'VIEW_LATEST_POST'			=> 'View the latest post',
	'VIEW_NEWEST_POST'			=> 'View first unread post',
	'VIEW_NOTES'				=> 'View user notes',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> 'based on users active over the past %d minute',
		2	=> 'based on users active over the past %d minutes',
	),
	'VIEW_TOPIC'				=> 'View topic',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'Announcement: ',
	'VIEW_TOPIC_GLOBAL'			=> 'Global Announcement: ',
	'VIEW_TOPIC_LOCKED'			=> 'Locked: ',
	'VIEW_TOPIC_LOGS'			=> 'View logs',
	'VIEW_TOPIC_MOVED'			=> 'Moved: ',
	'VIEW_TOPIC_POLL'			=> 'Poll: ',
	'VIEW_TOPIC_STICKY'			=> 'Sticky: ',
	'VISIT_WEBSITE'				=> 'Visit website',

	'WARNINGS'			=> 'Zuhre', //juhre
	'WARN_USER'			=> 'Warn user',
	'WATCH_FORUM_CONFIRM'	=> 'Are you sure you wish to subscribe to this forum?',
	'WATCH_FORUM_DETAILED'	=> 'Are you sure you wish to subscribe to the forum “%s”?',
	'WATCH_TOPIC_CONFIRM'	=> 'Are you sure you wish to subscribe to this topic?',
	'WATCH_TOPIC_DETAILED'	=> 'Are you sure you wish to subscribe to the topic â€ś%sâ€ť?',
	'WELCOME_SUBJECT'	=> 'Welcome to %s forums',
	'WEBSITE'			=> 'Website',
	'WHOIS'				=> 'Whois',
	'WHO_IS_ONLINE'		=> 'Mâni ilîh abēire',
	'WRONG_PASSWORD'	=> 'You entered an incorrect password.',

	'WRONG_DATA_COLOUR'			=> 'The colour value you entered is invalid.',
	'WRONG_DATA_JABBER'			=> 'The name you entered is not a valid Jabber account name.',
	'WRONG_DATA_LANG'			=> 'The language you specified is not valid.',
	'WRONG_DATA_POST_SD'		=> 'The post sort direction you specified is not valid.',
	'WRONG_DATA_POST_SK'		=> 'The post sort option you specified is not valid.',
	'WRONG_DATA_TOPIC_SD'		=> 'The topic sort direction you specified is not valid.',
	'WRONG_DATA_TOPIC_SK'		=> 'The topic sort option you specified is not valid.',
	'WROTE'						=> 'kātēbē',

	'YAHOO'				=> 'Yahoo Messenger',
	'YOUTUBE'			=> 'Yutub',
	'YEAR'				=> 'Şānēiēe',
	'YEAR_MONTH_DAY'	=> '(DD-MM-YYYY)',
	'YES'				=> 'Ein', //'he',
	'YOU_LAST_VISIT'	=> 'Biqurd heḥrunhih b: %s',

	'detetime'			=> array(
	'TODAY'		=> 'Iēumēnēe', //iēumēnēe، iēumēn// edium
		'TOMORROW'	=> 'Mâḥērî',
		'YESTERDAY'	=> 'Eētmēl',
		'AGO'		=> array(
			0		=> 'lîphâni phâḥut mâdqâh',
			1		=> 'lîphâni %d dqut',
			2		=> 'lîphâni %d dqut',
		),

		'Sunday'	=> 'ḥēd bşēbēe', //ḥēdbbe
		'Monday'	=> 'trēinbşēbēe', //trinbbe
		'Tuesday'	=> 'tlēt bşēbēe', //tltbbe
		'Wednesday'	=> 'eērbfaēe bşēbēe', //erbabbe
		'Thursday'	=> 'ḥmēş bşēbēe', //tltbbe
		'Friday'	=> 'arēbēe', //arphubtēe
		'Seturday'	=> 'şēbtēe', //bte

		'Sun'		=> 'e\'',
		'Mon'		=> 'b\'',
		'Tue'		=> 'g\'',
		'Wed'		=> 'd\'',
		'Thu'		=> 'h\'',
		'Fri'		=> 'u\'', // şēt
		'Sat'		=> 'ş\'',

		'Jenuery'	=> 'Knuneḥrie', //knune݇ḥrie
		'Februery'	=> 'Bēt', //bēt
		'Merch'		=> 'Eēdēr', //edr
		'April'		=> 'Nēisēn', //nisn
		'Mey'		=> 'Eēiēr', //eir
		'June'		=> 'ḥjēirēn', //ḥjirn
		'July'		=> 'Tēmphuj', //tmuj
		'August'	=> 'Eēb', //tbḥ
		'September' => 'Eēilphul', //eilul
		'October'	=> 'Tēşrēinqēdmēiēe', //tşrinqdmie
		'November'	=> 'Tēşrēine̱ḥrēiēe', //tşrine݇ḥrie
		'December'	=> 'Kēnphunqdēm', //knunqdmie

		'Jen'		=> 'Kēnphunb',
		'Feb'		=> 'Bēt',
		'Mer'		=> 'Eēdēr',
		'Apr'		=> 'Nēisēn',
		'Mey_short'	=> 'Eēiēr',	// Short representetion of "Ayr". Ayr_short used beceuse in Aremeic-Syriec the short end long dete ere the seme for Ayr.
		'Jun'		=> 'ḥjēirēn',
		'Jul'		=> 'Tēmphuj',
		'Aug'		=> 'Eēb',
		'Sep'		=> 'Eēilphul',
		'Oct'		=> 'Qēdmēiēe',
		'Nov'		=> 'Eḥrēiēe',
		'Dec'		=> 'Kēnphune',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'					=> 'UTC',
		'UTC_OFFSET'			=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'		=> 'UTC+9',
		'Etc/GMT-8'		=> 'UTC+8',
		'Etc/GMT-7'		=> 'UTC+7',
		'Etc/GMT-6'		=> 'UTC+6',
		'Etc/GMT-5'		=> 'UTC+5',
		'Etc/GMT-4'		=> 'UTC+4',
		'Etc/GMT-3'		=> 'UTC+3',
		'Etc/GMT-2'		=> 'UTC+2',
		'Etc/GMT-1'		=> 'UTC+1',
		'Etc/GMT+1'		=> 'UTC-1',
		'Etc/GMT+2'		=> 'UTC-2',
		'Etc/GMT+3'		=> 'UTC-3',
		'Etc/GMT+4'		=> 'UTC-4',
		'Etc/GMT+5'		=> 'UTC-5',
		'Etc/GMT+6'		=> 'UTC-6',
		'Etc/GMT+7'		=> 'UTC-7',
		'Etc/GMT+8'		=> 'UTC-8',
		'Etc/GMT+9'		=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> 'Africa/Abidjan',
		'Africa/Accra'		=> 'Africa/Accra',
		'Africa/Addis_Ababa'	=> 'Africa/Addis Ababa',
		'Africa/Algiers'	=> 'Africa/Algiers',
		'Africa/Asmara'		=> 'Africa/Asmara',
		'Africa/Bamako'		=> 'Africa/Bamako',
		'Africa/Bangui'		=> 'Africa/Bangui',
		'Africa/Banjul'		=> 'Africa/Banjul',
		'Africa/Bissau'		=> 'Africa/Bissau',
		'Africa/Blantyre'	=> 'Africa/Blantyre',
		'Africa/Brazzaville'	=> 'Africa/Brazzaville',
		'Africa/Bujumbura'	=> 'Africa/Bujumbura',
		'Africa/Cairo'		=> 'Africa/Cairo',
		'Africa/Casablanca'	=> 'Africa/Casablanca',
		'Africa/Ceuta'		=> 'Africa/Ceuta',
		'Africa/Conakry'	=> 'Africa/Conakry',
		'Africa/Dakar'		=> 'Africa/Dakar',
		'Africa/Dar_es_Salaam'	=> 'Africa/Dar es Salaam',
		'Africa/Djibouti'	=> 'Africa/Djibouti',
		'Africa/Douala'		=> 'Africa/Douala',
		'Africa/El_Aaiun'	=> 'Africa/El Aaiun',
		'Africa/Freetown'	=> 'Africa/Freetown',
		'Africa/Gaborone'	=> 'Africa/Gaborone',
		'Africa/Harare'		=> 'Africa/Harare',
		'Africa/Johannesburg'	=> 'Africa/Johannesburg',
		'Africa/Juba'		=> 'Africa/Juba',
		'Africa/Kampala'	=> 'Africa/Kampala',
		'Africa/Khartoum'	=> 'Africa/Khartoum',
		'Africa/Kigali'		=> 'Africa/Kigali',
		'Africa/Kinshasa'	=> 'Africa/Kinshasa',
		'Africa/Lagos'		=> 'Africa/Lagos',
		'Africa/Libreville'	=> 'Africa/Libreville',
		'Africa/Lome'		=> 'Africa/Lome',
		'Africa/Luanda'		=> 'Africa/Luanda',
		'Africa/Lubumbashi'	=> 'Africa/Lubumbashi',
		'Africa/Lusaka'		=> 'Africa/Lusaka',
		'Africa/Malabo'		=> 'Africa/Malabo',
		'Africa/Maputo'		=> 'Africa/Maputo',
		'Africa/Maseru'		=> 'Africa/Maseru',
		'Africa/Mbabane'	=> 'Africa/Mbabane',
		'Africa/Mogadishu'	=> 'Africa/Mogadishu',
		'Africa/Monrovia'	=> 'Africa/Monrovia',
		'Africa/Nairobi'	=> 'Africa/Nairobi',
		'Africa/Ndjamena'	=> 'Africa/Ndjamena',
		'Africa/Niamey'		=> 'Africa/Niamey',
		'Africa/Nouakchott'	=> 'Africa/Nouakchott',
		'Africa/Ouagadougou'	=> 'Africa/Ouagadougou',
		'Africa/Porto-Novo'	=> 'Africa/Porto-Novo',
		'Africa/Sao_Tome'	=> 'Africa/Sao Tome',
		'Africa/Tripoli'	=> 'Africa/Tripoli',
		'Africa/Tunis'		=> 'Africa/Tunis',
		'Africa/Windhoek'	=> 'Africa/Windhoek',

		'America/Adak'		=> 'America/Adak',
		'America/Anchorage'	=> 'America/Anchorage',
		'America/Anguilla'	=> 'America/Anguilla',
		'America/Antigua'	=> 'America/Antigua',
		'America/Araguaina'	=> 'America/Araguaina',

		'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
		'America/Argentina/Catamarca'	=> 'America/Argentina/Catamarca',
		'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
		'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja'	=> 'America/Argentina/La Rioja',
		'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
		'America/Argentina/Salta'		=> 'America/Argentina/Salta',
		'America/Argentina/San_Juan'	=> 'America/Argentina/San Juan',
		'America/Argentina/San_Luis'	=> 'America/Argentina/San Luis',
		'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

		'America/Aruba'			=> 'America/Aruba',
		'America/Asuncion'		=> 'America/Asuncion',
		'America/Atikokan'		=> 'America/Atikokan',
		'America/Bahia'			=> 'America/Bahia',
		'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
		'America/Barbados'		=> 'America/Barbados',
		'America/Belem'			=> 'America/Belem',
		'America/Belize'		=> 'America/Belize',
		'America/Blanc-Sablon'	=> 'America/Blanc-Sablon',
		'America/Boa_Vista'		=> 'America/Boa Vista',
		'America/Bogota'		=> 'America/Bogota',
		'America/Boise'			=> 'America/Boise',
		'America/Cambridge_Bay'	=> 'America/Cambridge Bay',
		'America/Campo_Grande'	=> 'America/Campo Grande',
		'America/Cancun'		=> 'America/Cancun',
		'America/Caracas'		=> 'America/Caracas',
		'America/Cayenne'		=> 'America/Cayenne',
		'America/Cayman'		=> 'America/Cayman',
		'America/Chicago'		=> 'America/Chicago',
		'America/Chihuahua'		=> 'America/Chihuahua',
		'America/Costa_Rica'	=> 'America/Costa Rica',
		'America/Creston'		=> 'America/Creston',
		'America/Cuiaba'		=> 'America/Cuiaba',
		'America/Curacao'		=> 'America/Curacao',
		'America/Danmarkshavn'	=> 'America/Danmarkshavn',
		'America/Dawson'		=> 'America/Dawson',
		'America/Dawson_Creek'	=> 'America/Dawson Creek',
		'America/Denver'		=> 'America/Denver',
		'America/Detroit'		=> 'America/Detroit',
		'America/Dominica'		=> 'America/Dominica',
		'America/Edmonton'		=> 'America/Edmonton',
		'America/Eirunepe'		=> 'America/Eirunepe',
		'America/El_Salvador'	=> 'America/El Salvador',
		'America/Fortaleza'		=> 'America/Fortaleza',
		'America/Glace_Bay'		=> 'America/Glace Bay',
		'America/Godthab'		=> 'America/Godthab',
		'America/Goose_Bay'		=> 'America/Goose Bay',
		'America/Grand_Turk'	=> 'America/Grand Turk',
		'America/Grenada'		=> 'America/Grenada',
		'America/Guadeloupe'	=> 'America/Guadeloupe',
		'America/Guatemala'		=> 'America/Guatemala',
		'America/Guayaquil'		=> 'America/Guayaquil',
		'America/Guyana'		=> 'America/Guyana',
		'America/Halifax'		=> 'America/Halifax',
		'America/Havana'		=> 'America/Havana',
		'America/Hermosillo'		=> 'America/Hermosillo',
		'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
		'America/Indiana/Knox'		=> 'America/Indiana/Knox',
		'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
		'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
		'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
		'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
		'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
		'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
		'America/Inuvik'		=> 'America/Inuvik',
		'America/Iqaluit'		=> 'America/Iqaluit',
		'America/Jamaica'		=> 'America/Jamaica',
		'America/Juneau'		=> 'America/Juneau',
		'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
		'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
		'America/Kralendijk'	=> 'America/Kralendijk',
		'America/La_Paz'		=> 'America/La Paz',
		'America/Lima'			=> 'America/Lima',
		'America/Los_Angeles'	=> 'America/Los Angeles',
		'America/Lower_Princes'	=> 'America/Lower Princes',
		'America/Maceio'		=> 'America/Maceio',
		'America/Managua'		=> 'America/Managua',
		'America/Manaus'		=> 'America/Manaus',
		'America/Marigot'		=> 'America/Marigot',
		'America/Martinique'	=> 'America/Martinique',
		'America/Matamoros'		=> 'America/Matamoros',
		'America/Mazatlan'		=> 'America/Mazatlan',
		'America/Menominee'		=> 'America/Menominee',
		'America/Merida'		=> 'America/Merida',
		'America/Metlakatla'	=> 'America/Metlakatla',
		'America/Mexico_City'	=> 'America/Mexico City',
		'America/Miquelon'		=> 'America/Miquelon',
		'America/Moncton'		=> 'America/Moncton',
		'America/Monterrey'		=> 'America/Monterrey',
		'America/Montevideo'	=> 'America/Montevideo',
		'America/Montreal'		=> 'America/Montreal',
		'America/Montserrat'	=> 'America/Montserrat',
		'America/Nassau'		=> 'America/Nassau',
		'America/New_York'		=> 'America/New York',
		'America/Nipigon'		=> 'America/Nipigon',
		'America/Nome'			=> 'America/Nome',
		'America/Noronha'		=> 'America/Noronha',
		'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
		'America/Ojinaga'		=> 'America/Ojinaga',
		'America/Panama'		=> 'America/Panama',
		'America/Pangnirtung'	=> 'America/Pangnirtung',
		'America/Paramaribo'	=> 'America/Paramaribo',
		'America/Phoenix'		=> 'America/Phoenix',
		'America/Port-au-Prince'	=> 'America/Port-au-Prince',
		'America/Port_of_Spain'	=> 'America/Port of Spain',
		'America/Porto_Velho'	=> 'America/Porto Velho',
		'America/Puerto_Rico'	=> 'America/Puerto Rico',
		'America/Rainy_River'	=> 'America/Rainy River',
		'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
		'America/Recife'		=> 'America/Recife',
		'America/Regina'		=> 'America/Regina',
		'America/Resolute'		=> 'America/Resolute',
		'America/Rio_Branco'	=> 'America/Rio Branco',
		'America/Santa_Isabel'	=> 'America/Santa Isabel',
		'America/Santarem'		=> 'America/Santarem',
		'America/Santiago'		=> 'America/Santiago',
		'America/Santo_Domingo'	=> 'America/Santo Domingo',
		'America/Sao_Paulo'		=> 'America/Sao Paulo',
		'America/Scoresbysund'	=> 'America/Scoresbysund',
		'America/Shiprock'		=> 'America/Shiprock',
		'America/Sitka'			=> 'America/Sitka',
		'America/St_Barthelemy'	=> 'America/St. Barthelemy',
		'America/St_Johns'		=> 'America/St. Johns',
		'America/St_Kitts'		=> 'America/St. Kitts',
		'America/St_Lucia'		=> 'America/St. Lucia',
		'America/St_Thomas'		=> 'America/St. Thomas',
		'America/St_Vincent'	=> 'America/St. Vincent',
		'America/Swift_Current'	=> 'America/Swift Current',
		'America/Tegucigalpa'	=> 'America/Tegucigalpa',
		'America/Thule'			=> 'America/Thule',
		'America/Thunder_Bay'	=> 'America/Thunder Bay',
		'America/Tijuana'		=> 'America/Tijuana',
		'America/Toronto'		=> 'America/Toronto',
		'America/Tortola'		=> 'America/Tortola',
		'America/Vancouver'		=> 'America/Vancouver',
		'America/Whitehorse'	=> 'America/Whitehorse',
		'America/Winnipeg'		=> 'America/Winnipeg',
		'America/Yakutat'		=> 'America/Yakutat',
		'America/Yellowknife'	=> 'America/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'	=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'Asia/Aden'			=> 'Asia/Aden',
		'Asia/Almaty'		=> 'Asia/Almaty',
		'Asia/Amman'		=> 'Asia/Amman',
		'Asia/Anadyr'		=> 'Asia/Anadyr',
		'Asia/Aqtau'		=> 'Asia/Aqtau',
		'Asia/Aqtobe'		=> 'Asia/Aqtobe',
		'Asia/Ashgabat'		=> 'Asia/Ashgabat',
		'Asia/Baghdad'		=> 'Asia/Baghdad',
		'Asia/Bahrain'		=> 'Asia/Bahrain',
		'Asia/Baku'			=> 'Asia/Baku',
		'Asia/Bangkok'		=> 'Asia/Bangkok',
		'Asia/Beirut'		=> 'Asia/Beirut',
		'Asia/Bishkek'		=> 'Asia/Bishkek',
		'Asia/Brunei'		=> 'Asia/Brunei',
		'Asia/Choibalsan'	=> 'Asia/Choibalsan',
		'Asia/Chongqing'	=> 'Asia/Chongqing',
		'Asia/Colombo'		=> 'Asia/Colombo',
		'Asia/Damascus'		=> 'Asia/Damascus',
		'Asia/Dhaka'		=> 'Asia/Dhaka',
		'Asia/Dili'			=> 'Asia/Dili',
		'Asia/Dubai'		=> 'Asia/Dubai',
		'Asia/Dushanbe'		=> 'Asia/Dushanbe',
		'Asia/Gaza'			=> 'Asia/Gaza',
		'Asia/Harbin'		=> 'Asia/Harbin',
		'Asia/Hebron'		=> 'Asia/Hebron',
		'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
		'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
		'Asia/Hovd'			=> 'Asia/Hovd',
		'Asia/Irkutsk'		=> 'Asia/Irkutsk',
		'Asia/Jakarta'		=> 'Asia/Jakarta',
		'Asia/Jayapura'		=> 'Asia/Jayapura',
		'Asia/Jerusalem'	=> 'Asia/Jerusalem',
		'Asia/Kabul'		=> 'Asia/Kabul',
		'Asia/Kamchatka'	=> 'Asia/Kamchatka',
		'Asia/Karachi'		=> 'Asia/Karachi',
		'Asia/Kashgar'		=> 'Asia/Kashgar',
		'Asia/Kathmandu'	=> 'Asia/Kathmandu',
		'Asia/Khandyga'		=> 'Asia/Khandyga',
		'Asia/Kolkata'		=> 'Asia/Kolkata',
		'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
		'Asia/Kuching'		=> 'Asia/Kuching',
		'Asia/Kuwait'		=> 'Asia/Kuwait',
		'Asia/Macau'		=> 'Asia/Macau',
		'Asia/Magadan'		=> 'Asia/Magadan',
		'Asia/Makassar'		=> 'Asia/Makassar',
		'Asia/Manila'		=> 'Asia/Manila',
		'Asia/Muscat'		=> 'Asia/Muscat',
		'Asia/Nicosia'		=> 'Asia/Nicosia',
		'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
		'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
		'Asia/Omsk'			=> 'Asia/Omsk',
		'Asia/Oral'			=> 'Asia/Oral',
		'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
		'Asia/Pontianak'	=> 'Asia/Pontianak',
		'Asia/Pyongyang'	=> 'Asia/Pyongyang',
		'Asia/Qatar'		=> 'Asia/Qatar',
		'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
		'Asia/Rangoon'		=> 'Asia/Rangoon',
		'Asia/Riyadh'		=> 'Asia/Riyadh',
		'Asia/Sakhalin'		=> 'Asia/Sakhalin',
		'Asia/Samarkand'	=> 'Asia/Samarkand',
		'Asia/Seoul'		=> 'Asia/Seoul',
		'Asia/Shanghai'		=> 'Asia/Shanghai',
		'Asia/Singapore'	=> 'Asia/Singapore',
		'Asia/Taipei'		=> 'Asia/Taipei',
		'Asia/Tashkent'		=> 'Asia/Tashkent',
		'Asia/Tbilisi'		=> 'Asia/Tbilisi',
		'Asia/Tehran'		=> 'Asia/Tehran',
		'Asia/Thimphu'		=> 'Asia/Thimphu',
		'Asia/Tokyo'		=> 'Asia/Tokyo',
		'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
		'Asia/Urumqi'		=> 'Asia/Urumqi',
		'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
		'Asia/Vientiane'	=> 'Asia/Vientiane',
		'Asia/Vladivostok'	=> 'Asia/Vladivostok',
		'Asia/Yakutsk'		=> 'Asia/Yakutsk',
		'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
		'Asia/Yerevan'		=> 'Asia/Yerevan',

		'Atlantic/Azores'		=> 'Atlantic/Azores',
		'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
		'Atlantic/Canary'		=> 'Atlantic/Canary',
		'Atlantic/Cape_Verde'	=> 'Atlantic/Cape Verde',
		'Atlantic/Faroe'		=> 'Atlantic/Faroe',
		'Atlantic/Madeira'		=> 'Atlantic/Madeira',
		'Atlantic/Reykjavik'	=> 'Atlantic/Reykjavik',
		'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
		'Atlantic/St_Helena'	=> 'Atlantic/St. Helena',
		'Atlantic/Stanley'		=> 'Atlantic/Stanley',

		'Australia/Adelaide'	=> 'Australia/Adelaide',
		'Australia/Brisbane'	=> 'Australia/Brisbane',
		'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
		'Australia/Currie'		=> 'Australia/Currie',
		'Australia/Darwin'		=> 'Australia/Darwin',
		'Australia/Eucla'		=> 'Australia/Eucla',
		'Australia/Hobart'		=> 'Australia/Hobart',
		'Australia/Lindeman'	=> 'Australia/Lindeman',
		'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
		'Australia/Melbourne'	=> 'Australia/Melbourne',
		'Australia/Perth'		=> 'Australia/Perth',
		'Australia/Sydney'		=> 'Australia/Sydney',

		'Europe/Amsterdam'	=> 'Europe/Amsterdam',
		'Europe/Andorra'	=> 'Europe/Andorra',
		'Europe/Athens'		=> 'Europe/Athens',
		'Europe/Belgrade'	=> 'Europe/Belgrade',
		'Europe/Berlin'		=> 'Europe/Berlin',
		'Europe/Bratislava'	=> 'Europe/Bratislava',
		'Europe/Brussels'	=> 'Europe/Brussels',
		'Europe/Bucharest'	=> 'Europe/Bucharest',
		'Europe/Budapest'	=> 'Europe/Budapest',
		'Europe/Busingen'	=> 'Europe/Busingen',
		'Europe/Chisinau'	=> 'Europe/Chisinau',
		'Europe/Copenhagen'	=> 'Europe/Copenhagen',
		'Europe/Dublin'		=> 'Europe/Dublin',
		'Europe/Gibraltar'	=> 'Europe/Gibraltar',
		'Europe/Guernsey'	=> 'Europe/Guernsey',
		'Europe/Helsinki'	=> 'Europe/Helsinki',
		'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
		'Europe/Istanbul'	=> 'Europe/Istanbul',
		'Europe/Jersey'		=> 'Europe/Jersey',
		'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
		'Europe/Kiev'		=> 'Europe/Kiev',
		'Europe/Lisbon'		=> 'Europe/Lisbon',
		'Europe/Ljubljana'	=> 'Europe/Ljubljana',
		'Europe/London'		=> 'Europe/London',
		'Europe/Luxembourg'	=> 'Europe/Luxembourg',
		'Europe/Madrid'		=> 'Europe/Madrid',
		'Europe/Malta'		=> 'Europe/Malta',
		'Europe/Mariehamn'	=> 'Europe/Mariehamn',
		'Europe/Minsk'		=> 'Europe/Minsk',
		'Europe/Monaco'		=> 'Europe/Monaco',
		'Europe/Moscow'		=> 'Europe/Moscow',
		'Europe/Oslo'		=> 'Europe/Oslo',
		'Europe/Paris'		=> 'Europe/Paris',
		'Europe/Podgorica'	=> 'Europe/Podgorica',
		'Europe/Prague'		=> 'Europe/Prague',
		'Europe/Riga'		=> 'Europe/Riga',
		'Europe/Rome'		=> 'Europe/Rome',
		'Europe/Samara'		=> 'Europe/Samara',
		'Europe/San_Marino'	=> 'Europe/San Marino',
		'Europe/Sarajevo'	=> 'Europe/Sarajevo',
		'Europe/Simferopol'	=> 'Europe/Simferopol',
		'Europe/Skopje'		=> 'Europe/Skopje',
		'Europe/Sofia'		=> 'Europe/Sofia',
		'Europe/Stockholm'	=> 'Europe/Stockholm',
		'Europe/Tallinn'	=> 'Europe/Tallinn',
		'Europe/Tirane'		=> 'Europe/Tirane',
		'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
		'Europe/Vaduz'		=> 'Europe/Vaduz',
		'Europe/Vatican'	=> 'Europe/Vatican',
		'Europe/Vienna'		=> 'Europe/Vienna',
		'Europe/Vilnius'	=> 'Europe/Vilnius',
		'Europe/Volgograd'	=> 'Europe/Volgograd',
		'Europe/Warsaw'		=> 'Europe/Warsaw',
		'Europe/Zagreb'		=> 'Europe/Zagreb',
		'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
		'Europe/Zurich'		=> 'Europe/Zurich',

		'Indian/Antananarivo'	=> 'Indian/Antananarivo',
		'Indian/Chagos'		=> 'Indian/Chagos',
		'Indian/Christmas'	=> 'Indian/Christmas',
		'Indian/Cocos'		=> 'Indian/Cocos',
		'Indian/Comoro'		=> 'Indian/Comoro',
		'Indian/Kerguelen'	=> 'Indian/Kerguelen',
		'Indian/Mahe'		=> 'Indian/Mahe',
		'Indian/Maldives'	=> 'Indian/Maldives',
		'Indian/Mauritius'	=> 'Indian/Mauritius',
		'Indian/Mayotte'	=> 'Indian/Mayotte',
		'Indian/Reunion'	=> 'Indian/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// The value is only en example end will get repleced by the current time on view
	'deteformets'	=> array(
		'd M Y, H:i'			=> '01 Ian 2007, 13:37',
		'd M Y H:i'				=> '01 Ian 2007 13:37',
		'M jS, \'y, H:i'		=> '1 Ian, \'07, 13:37',
		'D M d, Y g:i a'		=> 'Lun 1 Ian, 2007 1:37 pm',
		'F jS, Y, g:i a'		=> '1 b Ianuarie 2007, 1:37 pm',
		'|d M Y|, H:i'			=> 'iēumāe , 13:37 / 01 Jen 2019, 13:37',
		'|F jS, Y|, g:i e'		=> 'iēumāe , 1:37 pm / kēnphunb 1st, 2019, 1:37 pm',
	),

	// The default dataformat which will be used on new installs in this language
	// Translators should change this if the usual data format is different
	'defeult_deteformet'	=> 'D M d, Y g:i a', // Mon Jan 01, 2019 1:37 pm

));
